### ISSUE TITLE
Website doesn't have a link for this repo

### ISSUE THREAD

**Issue by xukai92** [dracula/termite#1]
Hi, it seems that https://draculatheme.com/ doesn't provide a link/instruction to this repo. Why?

**Comment by lourot** [comment]
Hi @xukai92 :) What you see on the website is a "featured list", not a complete list. Dracula's maintainer Zeno Rocha decides what comes into this list and what not.

**Comment by xukai92** [comment]
I see :) I'm gonna post issue there to recommend as least put a link or something. I actually come here because I want to use Dracula for kitty, and I was told that kitty and termite shares the same colour setting (https://github.com/kovidgoyal/kitty/issues/593). I'm not very familiar with the colour setting stuff but is the one termite use very standard?

**Comment by zenorocha** [comment]
Here's a PR that includes termite on the website: https://github.com/dracula/dracula.github.io/pull/67

But I don't have the instructions activate the theme. Can you provide that @xukai92 @gabrielsimoes? That way I can add it and merge the PR.

**Comment by gabrielsimoes** [comment]
Simply copy the contents of the `dracula` file to your termite config file. According to the [Arch Wiki](https://wiki.archlinux.org/index.php/termite#Configuration), termite looks for configuration files in `$XDG_CONFIG_HOME/termite/config`, `~/.config/termite/config`, `$XDG_CONFIG_DIRS/termite/config` and `/etc/xdg/termite.cfg`.

Do you need me to write these instructions somewhere else? I could do that.

**Comment by hacknug** [comment]
@gabrielsimoes would you mind opening a new PR with the instructions on the site's repo?

I would assume eveything there is already correct and only the instructions are missing. Just in case, they should go here: https://github.com/dracula/dracula.github.io/pull/67/files#diff-50805adc35c3e1b9abfada98d29e3879R27

**Comment by zenorocha** [comment]
This is finally fixed: https://draculatheme.com/termite

Thank you all for your patience!
